name: 'Slack Notify'
description: 'Send a message to slack'
branding:
  icon: message-square
  color: orange
inputs:
  channel:
    description: 'The Slack channel name. Required if no `channel_id` provided.'
    required: false
  channel_id:
    description: 'The Slack channel ID. Required if no `channel` provided.'
    required: false
  message:
    description: 'The status to list in the update.'
    required: true
  slot:
    description: 'The deployment slot of the Slack header.'
    required: false
  message_id:
    description: 'The ID of the existing Slack message to update.'
    required: false
  reason:
    description: 'Reason for the event'
    required: false
  branch:
    description: 'Branch name'
    required: false
  actor:
    description: 'Override the actor name.'
    required: false
outputs:
  message_id:
    description: 'The unique timestamp identifier of the Slack message sent. Used to update message.'
runs:
  using: 'node12'
  main: 'dist/index.js'
